image: docker

services:
  - docker:dind

stages:
  - test
  - deploy

test:
  stage: test
  only:
    - master
  script:
    - echo run tests in this section

step-deploy-prod:
  stage: deploy
  only:
    - master
  script:
    - sudo apt-get install -y python3-pip
    - sudo pip3 install --upgrade setuptools
    - sudo pip3 install docker-compose
    - sudo docker image prune -f
    - docker-compose -f docker-compose.prod.yml up -d --build
    - docker-compose -f docker-compose.prod.yml exec api python manage.py migrate --noinput
    - docker-compose -f docker-compose.prod.yml exec api python manage.py collectstatic --no-input --clear
  environment: production
  when: manual
