image: docker/compose:1.25.0-rc1

services:
  - docker:dind

stages:
  - test
  - deploy

test:
  stage: test
  only:
    - master
  script:
    - echo run tests in this section

step-deploy-prod:
  stage: deploy
  only:
    - master
  script:
    - sudo docker image prune -f
    - ls
    - docker-compose -f docker-compose.prod.yml up -d --build
    - docker-compose -f docker-compose.prod.yml exec -t api python manage.py migrate --noinput
    - docker-compose -f docker-compose.prod.yml exec -t api python manage.py collectstatic --no-input --clear
  environment: production
  when: manual
