version: '3.7'

services:
  api:
    build:
      context: ./lemma_rs_be
      dockerfile: Dockerfile.prod
    command: gunicorn lemma_rs_be.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/lemma_rs_be/api/staticfiles
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=lemmars
      - POSTGRES_USER=lemmars
      - POSTGRES_PASSWORD=lemmars
  fe:
    build:
      context: ./lemma-rs-fe
    ports: 
      - 8081:80
    networks: 
      - backbone 
      - default
  apisrv:
    build: ./lemma_rs_be/apiserver
    volumes:
      - static_volume:/home/lemma_rs_be/api/staticfiles
      - media_volume:/home/lemma_rs_be/api/mediafiles
    depends_on:
      - api
    networks: 
      - backbone
      - default
volumes:
  postgres_data:
  static_volume:
  media_volume:
networks:
    backbone:
      external: true    