version: '3.7'
    
services:
  db:
    ports: 
      - 5433:5432
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=lemmars
      - POSTGRES_USER=lemmars
      - POSTGRES_PASSWORD=lemmars