version: '3.7'
    
services:
  db:
    ports: 
      - 5433:5432
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=lemmars
      - POSTGRES_USER=lemmars
      - POSTGRES_PASSWORD=lemmars
  api:
    build:
      context: ./lemma_rs_be
    volumes:
      - ./lemma_rs_be:/code
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports: 
      - 8000:8000
volumes:
  postgres_data:
