# Generated by Django 3.2.2 on 2021-05-11 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='imageUrl',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='internalNotes',
            new_name='internal_notes',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='requiredPermissionLevel',
            new_name='required_permission_level',
        ),
    ]
