# Generated by Django 3.1.4 on 2021-02-20 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='fullname',
        ),
    ]
