# Generated by Django 3.2.2 on 2021-11-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='holidays',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
