# Generated by Django 3.1.4 on 2021-01-31 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
