# Generated by Django 3.2.2 on 2021-05-11 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0002_auto_20210511_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date_time', models.DateTimeField()),
                ('return_date_time', models.DateTimeField()),
                ('canceled', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_approved_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservedResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_return_date', models.DateTimeField(blank=True)),
                ('comment', models.CharField(default='', max_length=10000)),
                ('real_pickup_date', models.DateTimeField(blank=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rs.reservation')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.BooleanField(blank=True, default=None)),
                ('resolved_at', models.DateTimeField(blank=True)),
                ('response', models.CharField(max_length=10000)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicant', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permission_approved_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
