# Generated by Django 3.2.2 on 2021-11-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0002_user_holidays'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_notification_on_permission_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='send_notification_on_reservation_request',
            field=models.BooleanField(default=False),
        ),
    ]
