# Generated by Django 3.1.4 on 2021-02-20 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0002_auto_20210220_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
