# Generated by Django 3.2.2 on 2021-05-12 09:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0003_permissionrequest_reservation_reservedresource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissionrequest',
            old_name='result',
            new_name='approved',
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 12, 11, 2, 3, 811714)),
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='requested_level',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='rs.permissionlevel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_permission_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_permission_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
