# Generated by Django 3.2.2 on 2021-11-27 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0003_auto_20211121_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='provider',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='provided_reservations', to='rs.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
