# Generated by Django 3.2.2 on 2021-05-12 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0004_auto_20210512_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionrequest',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 12, 11, 10, 11, 488698)),
        ),
    ]
