# Generated by Django 3.2.2 on 2021-12-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0004_auto_20211127_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=160, null=True),
        ),
    ]
