# Generated by Django 3.2.2 on 2021-05-12 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0007_auto_20210512_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='canceled',
        ),
        migrations.AddField(
            model_name='reservation',
            name='picked_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='expiration_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reservedresource',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='rs.reservation'),
        ),
    ]
