# Generated by Django 3.2.2 on 2021-05-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0008_auto_20210513_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionrequest',
            name='response',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
