# Generated by Django 3.2.2 on 2021-05-13 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0010_alter_permissionrequest_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_approved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
