# Generated by Django 3.2.2 on 2021-05-13 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0011_alter_reservation_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedresource',
            name='real_pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservedresource',
            name='real_return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservedresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rs.resource'),
        ),
    ]
