# Generated by Django 3.2.2 on 2021-05-14 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0012_auto_20210514_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='rs.project'),
            preserve_default=False,
        ),
    ]
