# Generated by Django 3.2.2 on 2021-10-22 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rs', '0014_auto_20210516_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='inv_numbers',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='reservedresource',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='reservedresource',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='rs.reservation'),
        ),
    ]
